starport/courses/urls.py
from django.urls import path
from . import views

app_name = "courses"
urlpatterns = [
    # ex: /courses/
    path("", views.index, name="index"),
    # ex: /courses/1
    path("<int:cs_id>/", views.cs_detail, name="cs_detail"),
    # ex: /courses/1/1
    path("<int:cs_id>/<int:c_id>", views.c_detail, name="c_detail"),
    # ex: /courses/add
    path("add", views.add_to_queue, name="add_to_queue"),
    path("participation", views.participation, name="participation"),
    # Participate related paths
    path("<int:cs_id>/participate", views.participate, name="participate"),
    # Review List related paths
    path("review", views.ReviewList.as_view(), name="approval-review"),
    path("approved", views.approve_from_queue, name="approved"),
]

starport/starport/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views as core_views

urlpatterns = [
    path("", core_views.home, name="home"),
    path("login", auth_views.LoginView.as_view(), name="login"),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("auth/", include("social_django.urls", namespace="social")),
    path("settings/", core_views.user_settings, name="user_settings"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("courses/", include("courses.urls")),
    path("admin/", admin.site.urls),
]

starport/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}">
    <title>Starport</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Positif</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:participation' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Profile <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:index' %}">Discover</a>
                </li>

                {% if perms.courses.approve_course %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:approval-review' %}">Review</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Settings</a>
                </li>

            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
            </ul>

            {% endif %}
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div class="content container-fluid">
        {% block content %}
        {% endblock %}
    </div>
    </div>
    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

starport/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    {% if user.is_authenticated %}
    <h1>Hello, {{ user.username }}</h1>

    <ul>
        <li>Last login: {{  user.last_login  }}</li>
        <li>Joined: {{  user.date_joined  }}</li>
        <li>Staff: {{  user.is_staff  }}</li>
        {% if perms.courses.add %}
        <li>
            You can <a href="#">
                submit a course to Starport for community review.
            </a>
        </li>
        {% endif %}
        {% if perms.courses.approve_course %}
        <li>
            You can <a href="#">
                approve courses submitted by the community.
            </a>
        </li>
        {% endif %}
        <li>{{ user.get_all_permissions }}</li>
    </ul>


    {% else %}
    <p class="display-4">Hello, visitor</p>

    <p>Access to more than 100+ courses are completely free.
        Sign up for an account or <a class="lead" href="{% url 'login' %}">Log in</a> to continue.</p>

    {% endif %}
</div>

{% endblock content %}

starport/templates/settings.html
{% extends 'base.html' %}

{% block content %}
<h2>User Settings page</h2>

Your details:
<ul>
    <li>Username: {{ user.username }}</li>
    <li>Name: {{ user.first_name }}</li>
    {% if user.email %}
    <li>Email: {{ user.email }}</li>
    {% else %}
    We don't have your email on the system. <a href="/accounts/set_email/">Set your email</a> for account recovery and
    important notifications.
    {% endif %}
</ul>

<hr>

<h3>GitHub integration</h3>
<p>Connected as
    <a href="https://github.com/{{github_login.extra_data.login}}/" target='_blank'">
        {{ github_login.extra_data.login }}
    </a>
</p>

{% if github_login %}
{% if can_disconnect %}
    <form method=" post" action="{% url 'social:disconnect' 'github' %}">
        {% csrf_token %}
        <button type="submit">Disconnect from GitHub</button>
        </form>
        {% else %}
        <button type="button" disabled>Disconnect from GitHub</button>
        <p><span style="color: cadetblue;">You must <a href="/accounts/password_reset/">set a password</a> to disconnect
                from GitHub.</span></p>
        {% endif %}

        {% else %}
        <a href="{% url 'social:begin' 'github' %}">Connect to GitHub</a>
        {% endif %}





        {% endblock %}