starport/courses/urls.py
from django.urls import path
from . import views

app_name = "courses"
urlpatterns = [
    # ex: /courses/
    path("", views.index, name="index"),
    # ex: /courses/1
    path("<int:cs_id>/", views.cs_detail, name="cs_detail"),
    # ex: /courses/1/1
    path("<int:cs_id>/<int:c_id>", views.c_detail, name="c_detail"),
    # ex: /courses/add
    path("add", views.add_to_queue, name="add_to_queue"),
    path("participation", views.participation, name="participation"),
    # Participate related paths
    path("<int:cs_id>/participate", views.participate, name="participate"),
    # Review List related paths
    path("review", views.ReviewList.as_view(), name="approval-review"),
    path("approved", views.approve_from_queue, name="approved"),
]

starport/starport/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views as core_views

urlpatterns = [
    path("", core_views.home, name="home"),
    path("login", auth_views.LoginView.as_view(), name="login"),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("auth/", include("social_django.urls", namespace="social")),
    path("settings/", core_views.user_settings, name="user_settings"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("courses/", include("courses.urls")),
    path("admin/", admin.site.urls),
]

starport/courses/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class ApprovalQueue(models.Model):
    repo_url = models.SlugField("repo slug", unique=True)
    submitted_on = models.DateTimeField("submitted on", auto_now_add=True)
    submitted_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name="discovered"
    )
    approved_status = models.BooleanField("approved status", default=False)
    approved_by_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    class Meta:
        permissions = [
            (
                "approve_course",
                "Can approve a course submitted to the Queue by setting status as True",
            ),
            (
                "remove_course",
                "Can remove a course from the Queue by setting status as False",
            ),
        ]

        ordering = ["-submitted_on", "submitted_by"]

        def __str__(self):
            return self.repo_url


class CourseSet(models.Model):
    repo_url = models.SlugField("repo slug", unique=True)
    created_on = models.DateTimeField("created on", auto_now_add=True)
    updated_on = models.DateTimeField("last updated", auto_now=True)
    approved_by = models.OneToOneField(
        ApprovalQueue, on_delete=models.SET_NULL, null=True
    )
    owner = models.SlugField("owner")
    title = models.CharField("title", max_length=40)
    description = models.TextField(
        "description", max_length=300, default="No description yet"
    )
    image = models.URLField("repo image", null=True)
    course_n = models.PositiveSmallIntegerField(default=0)
    star_n = models.PositiveIntegerField(default=0)
    quizcontent = models.TextField()
    # TODO: reference to User model for owner?

    def __str__(self):
        return self.repo_url

    def updated_recently(self):
        return self.updated_on >= timezone.now() - datetime.timedelta(days=7)


class Course(models.Model):
    courseset = models.ForeignKey(CourseSet, on_delete=models.CASCADE)
    created_on = models.DateTimeField("created on", auto_now_add=True)
    updated_on = models.DateTimeField("last updated", auto_now=True)
    title = models.CharField("title", max_length=40)
    description = models.TextField(
        "description", max_length=300, default="No description yet"
    )
    star_n = models.PositiveIntegerField(default=0)
    course_url = models.URLField("course url")

    def __str__(self):
        return self.course_url

starport/quizdown/models.py
from django.utils.translation import ugettext_lazy as _
from django.db import models
from courses.models import CourseSet
from userprofile.models import UserProfile


class QuestionSet(models.Model):
    cs = models.OneToOneField(CourseSet, on_delete=models.CASCADE)
    passingscore = models.PositiveSmallIntegerField("passing score", default=1)
    maxscore = models.PositiveSmallIntegerField("max score", default=1)
    maxattempt = models.PositiveSmallIntegerField("max attempt", default=1)
    updated_on = models.DateTimeField("last updated", auto_now=True)


class UserQuizSubmission(models.Model):
    questionset = models.ForeignKey(QuestionSet, on_delete=models.SET_NULL, null=True)
    userprofile = models.ForeignKey(
        UserProfile, related_name="submitted_by", on_delete=models.CASCADE
    )
    last_submission_on = models.DateTimeField("last updated", auto_now=True)
    usermaxscore = models.PositiveSmallIntegerField("user max score", default=0)
    userattempt = models.PositiveSmallIntegerField("user attempt", default=0)

    def save(self, *args, **kwargs):

        if self.passingscore > self.maxscore:
            raise ValueError("passingscore can't be greater than maxscore")

        super().save(*args, **kwargs)

    class Meta:
        unique_together = [("questionset", "userprofile")]
        verbose_name = _("Question")
        verbose_name_plural = _("Questions")


class Question(models.Model):
    questionset = models.ForeignKey(QuestionSet, on_delete=models.CASCADE)
    prompt = models.TextField("question prompt", max_length=1000, blank=False)
    questionscore = models.PositiveSmallIntegerField("question score", default=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.CharField(
        max_length=1000, blank=False, help_text=_("Pick this choice?")
    )
    correct = models.BooleanField(
        blank=False, default=False, help_text=_("Is this the right answer?")
    )

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = _("Answer")
        verbose_name_plural = _("Answers")

starport/courses/forms.py
from django import forms
from .fields import repo_url_field


class AddtoQueueForm(forms.Form):
    repo_url = repo_url_field(label="GitHub URL", max_length=60)

    def clean(self):
        cleaned_data = super(AddtoQueueForm, self).clean()
        cleaned_url = cleaned_data.get("repo_url")
        # if cleaned_url:
        #     if cleaned_url[: cleaned_url.find("/")].lower() == "onlyphantom":
        #         msg = "onlyphantom adds his own repo."
        #         self.add_error("repo_url", msg)

starport/courses/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required

from .models import CourseSet, ApprovalQueue
from .forms import AddtoQueueForm
from quizdown.models import QuestionSet, Question, Choice


@login_required
def index(request):
    coursesets = CourseSet.objects.order_by("-updated_on")[:5]
    add_form = AddtoQueueForm()
    template = loader.get_template("courses/index.html")
    context = {"coursesets": coursesets, "add_form": add_form}

    return HttpResponse(template.render(context, request))


def cs_detail(request, cs_id):
    try:
        courseset = CourseSet.objects.get(pk=cs_id)
        questions = Question.objects.filter(questionset__cs=cs_id)
    except CourseSet.DoesNotExist:
        raise Http404("No project with that id.")
        # return render_to_response('custom_404_template.html')
    template = loader.get_template("courses/courseset.html")
    context = {"courseset": courseset, "questions": questions}
    return HttpResponse(template.render(context, request))


def c_detail(request, cs_id, c_id):
    return HttpResponse(f"The detail page for Course {c_id}")


@login_required
def participation(request):
    user = request.user
    coursesets = CourseSet.objects.filter(participated_by__user=user)
    template = loader.get_template("courses/participation.html")
    context = {"coursesets": coursesets}
    return HttpResponse(template.render(context, request))


def participate(request, cs_id):
    print(f"Participating {cs_id}")
    cs = get_object_or_404(CourseSet, pk=cs_id)
    template = loader.get_template("courses/courseset.html")
    context = {"courseset": cs}
    if "participate_btn" in request.POST:
        print(request.POST["participate_btn"])
        request.user.userprofile.participate.add(cs)
    else:
        request.user.userprofile.participate.remove(cs)
    return HttpResponse(template.render(context, request))


def add_to_queue(request):
    form = AddtoQueueForm(request.POST)
    if form.is_valid():
        repourl = request.POST["repo_url"].lower()
        existing_c = CourseSet.objects.filter(repo_url=repourl)
        if existing_c:
            return HttpResponse("Fail: This repo is already a course on Positif.io")
        existing_q = ApprovalQueue.objects.filter(repo_url=repourl)
        if existing_q:
            return HttpResponse(
                "Fail: This repo has already been submitted in the past."
            )
        else:
            ApprovalQueue(repo_url=repourl, submitted_by=request.user).save()
            return HttpResponseRedirect(reverse("courses:index"))
    else:
        template = loader.get_template("courses/index.html")
        coursesets = CourseSet.objects.order_by("-updated_on")[:5]
        add_form = AddtoQueueForm()
        context = {
            "coursesets": coursesets,
            "add_form": add_form,
            "error_message": form.errors,
        }
        return HttpResponse(template.render(context, request))


def approve_from_queue(request):
    if "approve_btn" in request.POST:
        repourl = request.POST["approve_btn"]
        print(f"{request.user} approved: {repourl}")
        approval_item = get_object_or_404(ApprovalQueue, repo_url=repourl)
        approval_item.approved_status = True
        approval_item.save(update_fields=["approved_status"])

    if "delete_btn" in request.POST:
        repourl = request.POST["delete_btn"]
        print(f"{request.user} deleted: {repourl}")
        approval_item = get_object_or_404(ApprovalQueue, repo_url=repourl)
        approval_item.delete()

    return HttpResponseRedirect(reverse("courses:approval-review"))


class ReviewList(ListView):
    model = ApprovalQueue
    template_name = "courses/approval.html"
    paginate = 10

    def get_queryset(self):
        return ApprovalQueue.objects.filter(approved_status=False)

starport/courses/templates/courses/approval.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Community Submission</h1>
    <h3>Submission pending approval</h3>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Submission</th>
                <th scope="col">Approval</th>
            </tr>
        </thead>
        {% for submission in object_list %}
        <tr class="{% cycle 'row1' 'row2' %}">
            <td>
                <small>{{ submission.submitted_on|date:"D, d M" }}</small>
                <h6>
                    <a href='https://github.com/{{submission.repo_url}}' target="_blank">
                        {{ submission.repo_url|upper}}
                    </a>
                </h6>

                Submitted by: <em>{{ submission.submitted_by }}</em>
            </td>
            <td>
                <form action="{% url 'courses:approved' %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-primary" type="submit" value="{{ submission.repo_url }}" name="approve_btn">
                        Approve</button>
                    <button class="btn btn-outline-danger" type="submit" value="{{ submission.repo_url }}"
                        name="delete_btn">
                        Delete from Queue</button>
                </form>
            </td>

        </tr>

        {% empty %}
        <span>No pending submission.</span>
        {% endfor %}
    </table>
</div>


{% endblock content %}

starport/courses/templates/courses/courseset.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row mt-4">
        <div class="col-4" id="sticky-sidebar">
            <div class="sticky-top flex-grow-1">
                <div class="nav flex-sm-column">
                    <h1>{{ courseset.title }}</h1>
                    <p>{{ courseset.description }}<br>
                        <small>Last Queried: {{ courseset.updated_on }}</small></p>
                    <p>Producer: {{ courseset.owner }}</p>


                    <div class="mt-2">

                        <!-- Place this tag where you want the button to render. -->
                        <a class="github-button" href="https://github.com/{{courseset.repo_url}}" data-size="large"
                            data-show-count="true" aria-label="Star {{courseset.repo_url}} on GitHub">Star</a>
                        <!-- Place this tag where you want the button to render. -->
                        <a class="github-button" href="https://github.com/{{courseset.owner}}" data-size="large"
                            data-show-count="true" aria-label="Follow @{{courseset.owner}} on GitHub">Follow
                            @{{courseset.owner}}</a>


                    </div>
                    <hr>
                    <div class="mt-2">
                        <form action="{% url 'courses:participate' courseset.id %}" method="post">
                            {% csrf_token %}
                            {% if courseset not in user.userprofile.participate.all %}
                            <button class="btn btn-primary btn-lg btn-block" type="submit"
                                value="{{ submission.repo_url }}" name="participate_btn">
                                Participate</button>
                            {% else %}
                            <button class="btn btn-primary btn-lg btn-block" type="submit"
                                value="{{ submission.repo_url }}" name="unparticipate_btn">
                                Unparticipate</button>
                            {% endif %}
                        </form>

                        <form action="">
                            {% if user.username == courseset.owner %}
                            <button class="btn btn-dark btn-lg btn-block" type="submit"
                                value="{{ submission.repo_url }}" name="add_quiz_btn">Add Quiz</button>
                            {% else %}
                            <p>You can participate in this project.</p>
                            {% endif %}
                        </form>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-8" id="main">
            <div class="jumbotron">
                <h1>{{ courseset.title }}</h1>
                <ul class="nav nav-pills mb-4" id="courseset-tab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="content-tab" data-toggle="tab" href="#content" role="tab"
                            aria-controls="content" aria-selected="true">Content</a></li>
                    <li><a class="nav-link" id="quiz-tab" data-toggle="tab" href="#quiz" role="tab" aria-controls="quiz"
                            aria-selected="false">Quiz</a></li>
                    <li><a class="nav-link" id="recipients-tab" data-toggle="tab" href="#recipients" role="tab"
                            aria-controls="recipients" aria-selected="false">Recipients</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="content" role="tabpanel" aria-labelledby="content-tab">
                        {{ courseset.quizcontent | safe }}
                        <ol>
                            {% for quiz in questions %}
                            <li class="{% cycle 'row1' 'row2' %} mt-4">
                                <h6>Quiz {{ forloop.counter }}</h6>

                                <p>{{ quiz.prompt }}</p>
                                <select name="choice" id="choice_option">
                                    {% for choice in quiz.choice_set.all %}
                                    <option value="{{ choice.content }}">{{ choice.content }}</option>
                                    {% endfor %}
                                </select>
                                <!-- Select:
                                    <ul>
                                        {% for choice in quiz.choice_set.all %}
                                        <li>{{ choice.content }}</li>
                                        {% endfor %}
                                    </ul> -->

                                <div class="mb-4 mt-2">
                                    <strong>Question worth <u>{{ quiz.questionscore }} point</u></strong>
                                </div>
                                <hr>
                            </li>
                            {% empty %}
                            <li>No quiz associated with this project.</li>

                            {% endfor %}
                        </ol>
                    </div>
                    <div class="tab-pane fade" id="quiz" role="tabpanel" aria-labelledby="quiz-tab">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu nisi dolor. Donec a
                            ultrices massa.
                            Sed sit amet varius neque. Aenean in libero pretium, sollicitudin purus eget, feugiat nunc.
                            Integer
                            tortor dolor, maximus eget commodo tempus, congue eu est. Praesent molestie odio sapien, id
                            mollis
                            nisi efficitur eget. <br>Maecenas sapien sapien, laoreet non imperdiet eu, malesuada quis
                            sapien.
                            Aenean
                            luctus tristique lacus ut tempus. Donec vestibulum odio dignissim, vestibulum tellus vel,
                            suscipit
                            magna. Donec sed sem ex. <br>Sed rhoncus eu nisl at sodales. Aenean ac mattis ligula, eu
                            tincidunt
                            lectus. Donec auctor accumsan nibh, et congue augue sagittis tempus. Nunc suscipit viverra
                            elit.
                        </p>
                    </div>
                    <div class="tab-pane fade" id="recipients" role="tabpanel" aria-labelledby="recipients-tab">
                        <h3>Users with passing score on {{ courseset.title }}</h3>
                        <ul>
                            <li><a href="#">onlyphantom</a></li>
                        </ul>
                    </div>
                </div>


                <button class="btn btn-primary btn-lg btn-block" type="submit" value="{{ submission.repo_url }}"
                    name="add_quiz_btn">Submit Quiz</button>
                {% if user.username == courseset.owner %}
                <button class="btn btn-dark btn-lg btn-block" type="submit" value="{{ submission.repo_url }}"
                    name="add_quiz_btn">Set Answers</button>
                {% else %}
                <p>You can participate in this project.</p>
                {% endif %}
            </div>

        </div>
    </div>

</div>



<ul>
    {% for course in courseset.course_set.all %}
    <li>
        <a href="{% url 'courses:c_detail' course.id %}">{{ course.title }}</a>
    </li>
    {% endfor %}
</ul>
{% endblock content %}

starport/courses/templates/courses/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <div class="jumbotron">
        <form action="{% url 'courses:add_to_queue' %}" method="POST">
            {% csrf_token %}
            <h3>Submit a repo to the approval queue</h3>
            {{ add_form }}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>

    {% if coursesets %}
    <h1>Projects on Starport</h1>

    <div class="row">
        {% for courseset in coursesets %}
        <div class="col-4">
            <span>
                <a href="{% url 'courses:cs_detail' courseset.id %}">
                    {{ courseset.title }}
                </a>
            </span>
            <div>
                {{ courseset.description }}
            </div>
            <div>
                <span>{{ courseset.owner }} | {{ courseset.course_n }}</span>
            </div>

        </div>
        {% endfor %}
    </div>

    {% else %}
    <p>No courses available at the moment!</p>
    {% endif %}

</div>
{% endblock %}

starport/courses/templates/courses/participation.html
{% extends "base.html" %}

{% block content %}

<div class="container mt-4">
    {% if coursesets %}
    <h1>My Projects</h1>
    <p>Participate in a project to have it listed under "My Projects".</p>
    <hr>

    <div class="row">
        {% for courseset in coursesets %}
        <div class="col-4">
            <span>
                <a href="{% url 'courses:cs_detail' courseset.id %}">
                    {{ courseset.title }}
                </a>
            </span>
            <div>
                {{ courseset.description }}
            </div>
            <div>
                <span>{{ courseset.owner }} | {{ courseset.course_n }}</span>
            </div>

        </div>
        {% endfor %}
    </div>

    {% else %}
    <p>You haven't participated in any projects! Shall we recommend some?</p>
    {% endif %}

</div>
{% endblock %}